# Generated by Django 4.1.7 on 2023-05-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("under_analysis", "Under Analysis"),
                ],
                default="under_analysis",
                max_length=50,
            ),
        ),
    ]
