# Generated by Django 4.1.7 on 2023-05-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_alter_applicant_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="avatar",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
