# Generated by Django 4.1.7 on 2023-05-22 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_alter_applicant_age_alter_applicant_cv_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("under_analysis", "Under Analysis"),
                        ],
                        default="under_analysis",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="applicant",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="applications.status",
            ),
        ),
    ]
