# Generated by Django 4.1.7 on 2023-05-24 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0005_alter_applicant_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="status",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="applications.status",
            ),
        ),
    ]
