# Generated by Django 4.1.7 on 2023-05-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0006_alter_applicant_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="role",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
